import { GetStaticPaths, GetStaticProps, InferGetStaticPropsType } from 'next';
import Head from 'next/head';
import { ParsedUrlQuery } from 'querystring';
import React from 'react';
import { BLOG_DIR, getData } from '../../lib/md';

const PostDetailPage: React.FC = ({
  slug,
  post,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <>
      <Head>
        <title>Post - {slug}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <pre>{post.content}</pre>
    </>
  );
};

export const getStaticPaths: GetStaticPaths = async () => {
  const metaData = getData(BLOG_DIR);

  return {
    paths: metaData.map((data) => ({ params: { slug: data.slug } })),
    fallback: 'blocking',
  };
};

export const getStaticProps: GetStaticProps = async (context) => {
  const { slug } = context.params as ParsedUrlQuery;
  const posts = getData(BLOG_DIR);

  return {
    props: {
      slug,
      post: posts.find((post) => post.slug === slug),
    },
  };
};

export default PostDetailPage;
