import {GetStaticPaths, GetStaticProps, InferGetStaticPropsType} from 'next';
import React from 'react';
import {BLOG_DIR, getMetaData} from '../../lib/md';
import {ParsedUrlQuery} from 'querystring';
import Head from 'next/head';

const PostDetailPage: React.FC = ({
  slug,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <>
      <Head>
        <title>Post - {slug}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 role="heading">{slug}</h1>
    </>
  );
};

export const getStaticPaths: GetStaticPaths = async () => {
  const metaData = getMetaData(BLOG_DIR);

  return {
    paths: metaData.map((data) => ({params: {slug: data.slug}})),
    fallback: 'blocking',
  };
};

export const getStaticProps: GetStaticProps = async (context) => {
  const {slug} = context.params as ParsedUrlQuery;

  return {
    props: {
      slug,
    },
  };
};

export default PostDetailPage;
