import Head from 'next/head';
import {POST_DIR, getSlugs} from '../lib/mdx';
import {GetStaticProps, InferGetStaticPropsType} from 'next';

export const getStaticProps: GetStaticProps = async (context) => {
  const slugs = getSlugs(POST_DIR);

  return {
    props: {
      slugs,
    },
  };
};

export default function Home({
  slugs,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-inter">
        <ul>
          {slugs.map((slug: string) => (
            <li key={slug}>{slug}</li>
          ))}
        </ul>
      </main>
    </>
  );
}
