import { GetStaticProps, InferGetStaticPropsType } from 'next';
import Head from 'next/head';
import { BLOG_DIR, getMetaData } from '../lib/md';
import Link from 'next/link';
import { IFrontMatter } from '../types/blog-post';
import PostItem from '../components/PostItem';

export const getStaticProps: GetStaticProps = async () => {
  const posts = getMetaData(BLOG_DIR);

  return {
    props: {
      posts,
    },
  };
};

export default function Home({
  posts,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4"></div>
      <ul role="list">
        {posts.map((post: IFrontMatter) => (
          <PostItem key={post.slug} {...post} />
        ))}
      </ul>
    </>
  );
}
