import {GetStaticProps, InferGetStaticPropsType} from 'next';
import Head from 'next/head';
import {BLOG_DIR, getSlugs} from '../lib/md';
import Link from 'next/link';

export const getStaticProps: GetStaticProps = async (context) => {
  const slugs = getSlugs(BLOG_DIR);

  return {
    props: {
      slugs,
    },
  };
};

export default function Home({
  slugs,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="font-inter">
        <ul role="list">
          {slugs.map((slug: string, idx: number) => (
            <li key={idx} role="listitem" className="cursor-pointer">
              <Link href={`/posts/${slug}`}>{slug}</Link>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
}
